### PR TITLE
Avoid refering to $HOME

### PR DESCRIPTION
**Pull request by waltercool**
Removing home, adding reference to project instead.

### CODE REVIEW

**Comment by AndyCGYan** [comment]
Not sure if I want to merge this... What kind of issue would referring to ~ pose?

**Comment by waltercool** [comment]
It's because the README.md explains to run the build script if you want the system outputs, but the script will fail "unless" you have everything at your $HOME path (~).

This patch replaces the absolute $HOME path for a relative one instead, using the same $BL variable (which already points to $PWD/treble_build_los).

**Comment by Kyuunex** [comment]
Just came here to make a pull request about the exact same thing but i see you beat me to it. 
I was cloning everything somewhere else, so the patches were not applying, took me a long time and a failed build to realize this.
There is no real reason anything should refer to $HOME

**Comment by AndyCGYan** [comment]
There is a real reason I want to have treble_experimentations (and sas-creator in the upcoming LOS18) separate from the workspace though - it's a common building block for all GSIs, so I want to avoid having to clone and maintain one inside every workspace.

Also, isn't `$BL/..` just `$PWD`?

**Comment by waltercool** [comment]
The reason why I'm proposing the change, is because README.md suggest to use the build bot script.

> Finally, start the build script:
> 
> bash treble_build_los/buildbot_treble.sh
> 
> Be sure to update the cloned repos from time to time!

Related to $BL/..equal to $PWD, yes, the reason was to re-use variables already in use for easier maintenance. If $BL changes in future, so no extra change would be required.

**Comment by AndyCGYan** [comment]
The new unified script doesn't use `$BL` anymore; the need of a common `treble_experimentations` still stands. Closing this for now.

**Pull request closed without merging**
